### ISSUE TITLE
Make amount as an optional in the PayForm

### ISSUE THREAD

**Issue by gsammi** [bambora-na/checkoutfields#3]

**Comment by bowens-bambora** [comment]
This could be a possibility. I'll look into adding it as a feature for the next release as long as it doesn't affect the PayForm UI too drastically.

In this mean time you can use the PayFields functionality to collect straight card data, without email or amount.

**Comment by aengusbates** [comment]
Payform product has been deprecated. Payfields (now CheckoutFields) product will be supported and enhanced. Closing enhancement request.
