### ISSUE TITLE
Provide Client Side Validation for Billing Address

### ISSUE THREAD

**Issue by jperanson** [bambora-na/checkoutfields#72]
### Expected behaviour:

State and country fields in payform should be drop downs so that users enter a valid state and country.  

### Actual behaviour:
Payform rejects all (valid) addresses except those that use the the valid two-digit state and country codes used by the beanstream backend.

Error message returned: "Payment Failed: Missing or invalid payment information - Please validate all required payment information."

### Steps to reproduce:
set data-billingAddress=“true”

Enter in address of 
10 Anywhere St
New York, New York
11121
United States

### Browsers:
All

**Comment by aengusbates** [comment]
Hi Jason,

Agreed. This is a known limitation and is a prerequisite for interop with Payment Profiles. I'm flagging this as an enhancement.

**Comment by aengusbates** [comment]
Payform product has been deprecated. Payfields (now CheckoutFields) product will be supported and enhanced. Closing enhancement request.
