### ISSUE TITLE
Credit Card CVV accepts the special character of %%%

### ISSUE THREAD

**Issue by Rich1963** [bambora-na/checkoutfields#74]
### Expected behaviour:

Should only accept numeric values as CVV
As far as I know CVV should be numeric values only

------------------------------------------

The CVV Number ("Card Verification Value") on your credit card or debit card is a 3 digit number on VISA®, MasterCard® and Discover® branded credit and debit cards. On your American Express® branded credit or debit card it is a 4 digit numeric code.

------------------------------------------

### Actual behaviour:

% can be used in its entirety or partial in the CVV and processes credit card payments.

i.e. Visa CVV = 3 digits  Will accept %%% or 12% as the CVV value. 

### Steps to reproduce:

Enter a credit card number for either brands and for the CVV use %%% or 1%3 and the system will process the payment.

### Browsers:

Chrome

**Comment by jasonsperske** [comment]
It will also accept `'` and `.`

**Comment by aengusbates** [comment]
Resolved in latest release.
