### ISSUE TITLE
Names with apostrophies result in a "Please enter your full name." error

### ISSUE THREAD

**Issue by jasonsperske** [bambora-na/checkoutfields#76]
### Expected behavior:

When I enter a name such as "Adam D'Angelo" (https://en.wikipedia.org/wiki/Adam_D%27Angelo) along with all required fields I expect to be able to complete a transaction.

### Actual behavior:

Pressing the "Pay" button instead results in an an error

### Steps to reproduce:

Enter a name with an apostrophe such as "Adam D'Angelo" and fill in all other fields.

### Browsers:

Tested on Firefox but this behavior is the result of the following regex (found on line 605 in https://payform.beanstream.com/tokenizationform/js/script.js)

    ^[a-zA-Z]+(?:(?:\s+|-)[a-zA-Z]+)*$

So the behavior should appear in all browsers.

**Comment by aengusbates** [comment]
Payform product has been deprecated. Payfields (now CheckoutFields) product will be supported and enhanced. Closing enhancement request.
